//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypozyczalniaNarty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klienci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klienci()
        {
            this.Transakcjes = new HashSet<Transakcje>();
        }
    
        public int KlientId { get; set; }
        public string KlientImie { get; set; }
        public string KlientNazwisko { get; set; }
        public decimal KlientPesel { get; set; }
        public decimal KlientTel { get; set; }
        public string KlientMail { get; set; }
        public string KlientLogin { get; set; }
        public string KlientPassword { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transakcje> Transakcjes { get; set; }
    }
}
