//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WypozyczalniaNarty.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transakcje
    {
        public int TransakcjaId { get; set; }
        public int NartaId { get; set; }
        public int KlientId { get; set; }
        public System.DateTime TransakcjaData { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Narty Narty { get; set; }
    }
}
